command_timeout = 5000
format = """
[‚ñë‚ñí‚ñì](#a3aed2)\
[ ‚ôªÔ∏è ](bg:#a3aed2 fg:#090c0c)\
[ÓÇ¥](bg:#769ff0 fg:#a3aed2)\
$directory\
[ÓÇ¥](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[ÓÇ¥](fg:#394260 bg:#212736)\
$rust\
$golang\
$python\

[ÓÇ¥](fg:#212736 bg:#1d2230)\
$time\
[ÓÇ¥ ](fg:#1d2230)\
\n$character"""

add_newline = true

[character]
error_symbol = '[‚ÄºÔ∏è‚ÄºÔ∏è](bold red)'

[cmd_duration]
min_time = 5000
format = 'elapsed [$duration](bold orange)'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold orange)'
disabled = false

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "‚Ä¶/"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "

[git_branch]
symbol = "Ôêò"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

# [nodejs]
# symbol = "Óúò"
# style = "bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# [rust]
# symbol = "Óû®"
# style = "bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# [python]
# symbol = "üêç"
# style = "bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# [golang]
# symbol = "Óòß"
# style = "bg:#212736"
# format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ Ôê∫ $time ](fg:#a0a9cb bg:#1d2230)]($style)'
